// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwHgUYWIan-USdr4PJN024A_vu_89m2wg',
    appId: '1:1008816734137:web:3bdfa7d398283d68984068',
    messagingSenderId: '1008816734137',
    projectId: 'eaziline-500e2',
    authDomain: 'eaziline-500e2.firebaseapp.com',
    storageBucket: 'eaziline-500e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-ey_nXWabbXMMSJotmnTLqpoqfWDPuA',
    appId: '1:1008816734137:android:bff2cd80c15fe078984068',
    messagingSenderId: '1008816734137',
    projectId: 'eaziline-500e2',
    storageBucket: 'eaziline-500e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2obzJKd6MuGprFpUDAHzW4jXXOisZCIs',
    appId: '1:1008816734137:ios:80f540c63b3d3228984068',
    messagingSenderId: '1008816734137',
    projectId: 'eaziline-500e2',
    storageBucket: 'eaziline-500e2.appspot.com',
    iosClientId: '1008816734137-qbkff595n09ri51murcgpe9ehv8r5sac.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaziline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2obzJKd6MuGprFpUDAHzW4jXXOisZCIs',
    appId: '1:1008816734137:ios:91704729f916fa74984068',
    messagingSenderId: '1008816734137',
    projectId: 'eaziline-500e2',
    storageBucket: 'eaziline-500e2.appspot.com',
    iosClientId: '1008816734137-8vs0hqh6of05skct9t5mlek5tl7n08g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaziline.RunnerTests',
  );
}
